### PR TITLE
fix: Do not run istio-install target by default

### PR DESCRIPTION
**Pull request by jsuchome**
It is supposed to be installed by fuseml-installer

### CODE REVIEW

**Comment by flaviodsr** [comment]
You will probably also need to change the order of installation, fuseml should be installed before seldon, kfserving, knative...

**Comment by jsuchome** [comment]
seldon, kfserving, knative... are still installed by Makefile, installer does not handle them

**Comment by flaviodsr** [comment]
Yes, but the sequence is defined here: https://github.com/fuseml/fuseml/blob/main/acceptance/acceptance_suite_test.go#L86

If you are leaving istio to be installed by FuseML, anything that depends on istio will fail to be installed because they are being installed before FuseML.

**Comment by jsuchome** [comment]
ah, right

**Review by flaviodsr — APPROVED** [review]

**Pull request merged**
